### ISSUE TITLE
Empty message

### ISSUE THREAD

**Issue by Wawoul** [venam/tg-bot#3]
Hey I really like the idea of the clever bot lua you have in this. But i cant seem to make it work with the cleverbot() command as I'm getting empty message error.

Cheers

**Comment by venam** [comment]
> Hey I really like the idea of the clever bot lua you have in this. But i cant seem to make it work with the cleverbot() command as I'm getting empty message error.

The cleverbot command depends on a third party script. Check if it's in the location specified by lua.
 
> Was wondering if there was a way to combine make it its own plugin that i can use with https://github.com/venam/ bot?
I don't understand what you mean by this, care to clarify?


-- 
Patrick Louis <patrick@iotek.org>

**Comment by Wawoul** [comment]
Hmm still having no luck with it, even in the correct location. Even getting the error with the other commands.

Forget the bottom part, I didn't mean to type that here.

**Comment by venam** [comment]
The third party cleverbot script that I have in the repo is outdated and gives a 404 error.
